binge/forms.py
from flask_wtf import FlaskForm
from wtforms import SelectField, StringField, SubmitField
from wtforms.validators import DataRequired


class QueryForm(FlaskForm):
    title = StringField(
        "Title", validators=[DataRequired()], render_kw={"placeholder": "Teletubbies"}
    )
    find_it = SubmitField()


class PeroidForm(FlaskForm):
    minutes_in_day = 1440

    duration = StringField(
        "Requested duration",
        validators=[DataRequired()],
        render_kw={"placeholder": "7"},
        default="7",
    )
    peroid = SelectField(
        "Peroid",
        choices=[
            (minutes_in_day, "days"),
            (minutes_in_day * 7, "weeks"),
            (minutes_in_day * 30, "months"),
        ],
        default="days",
    )
    go = SubmitField()

binge/__init__.py
# !/bin/python3
# isort: skip_file
import os
import secrets

from flask import Flask

from flask_session import Session
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()


def create_app(test_config=None):
    app = Flask(__name__, instance_relative_config=True)
    app.config.from_mapping(
        SECRET_KEY=secrets.token_hex(16),
    )

    app.config["SESSION_PERMANENT"] = False
    app.config["SESSION_TYPE"] = "filesystem"
    app.config["SQLALCHEMY_DATABASE_URI"] = "sqlite:///binge.db"
    _session = Session()
    _session.init_app(app)

    if test_config is None:
        app.config.from_pyfile("config.py", silent=True)
    else:
        app.config.from_mapping(test_config)

    try:
        os.makedirs(app.instance_path)
    except OSError as err:
        print(err)

    from . import routes

    app.register_blueprint(routes.bp)

    db.init_app(app)

    with app.app_context():
        db.create_all()

    return app

binge/app/routes.py
from api_connector import requester
from flask import redirect, render_template, session, url_for
from forms import PeroidForm, QueryForm
from run import app


@app.route("/", methods=["GET", "POST"])
def main_page():
    form = QueryForm()
    if form.validate_on_submit():
        title = form.title.data
        title_id = requester.get_id_by_phrase(phrase=title)
        title_data = requester.get_title_data(title_id)
        session["title_data"] = title_data
        return redirect(url_for("title_page"))
    return render_template("home.html", form=form)


@app.route("/title", methods=["GET", "POST"])
def title_page():
    form = PeroidForm()
    title_data = session.get("title_data")
    if form.validate_on_submit():
        title_duration = requester.get_title_duration(title_data["id"])
        title_duration = title_duration
        peroid = form.peroid.data
        duration = form.duration.data
        session["message"] = _check_if_can_be_binged(
            int(peroid), int(duration), title_duration
        )
        return redirect(url_for("answer"))
    return render_template("title.html", form=form)


def _check_if_can_be_binged(peroid: int, duration: int, title_duration: int) -> str:
    time_to_binge = duration * peroid
    if title_duration > time_to_binge:
        return "It's impossible!"
    else:
        return "Go ahead, you can make it!"


@app.route("/answer", methods=["GET", "POST"])
def answer():
    return render_template("answer.html")


@app.route("/about", methods=["GET"])
def about():
    return render_template("about.html")

binge/routes.py
from flask import Blueprint, redirect, render_template, session, url_for

from binge.api_connector import Requester
from binge.forms import PeroidForm, QueryForm

bp = Blueprint("routes", __name__)
requester = Requester()


@bp.route("/", methods=["GET", "POST"])
def main_page():
    form = QueryForm(prefix="form")
    if form.validate_on_submit():
        _get_title_data(form=form)
        return redirect(url_for("routes.title_page"))
    return render_template("home.html", form=form)


def _get_title_data(form: QueryForm) -> None:
    title = form.title.data
    title_id = requester.get_id_by_phrase(phrase=title)
    session["title_data"] = requester.get_title_data(title_id)
    return None


@bp.route("/title", methods=["GET", "POST"])
def title_page():
    form = PeroidForm(prefix="form")
    title_data = session.get("title_data")
    if form.validate_on_submit():
        _create_message(form=form, title_data=title_data)
        return redirect(url_for("routes.answer"))
    return render_template("title.html", form=form, title_data=title_data)


def _create_message(form: PeroidForm, title_data: dict) -> None:
    title_duration = requester.get_title_duration(
        title_data["id"], int(title_data["seasons"])
    )
    peroid = int(form.peroid.data)
    duration = int(form.duration.data)
    session["message"] = _check_if_can_be_binged(peroid, duration, title_duration)
    return None


def _check_if_can_be_binged(peroid: int, duration: int, title_duration: int) -> str:
    time_to_binge = duration * peroid
    if title_duration > time_to_binge:
        return "It's impossible!"
    else:
        return "Go ahead, you can make it!"


@bp.route("/answer", methods=["GET", "POST"])
def answer():
    message = session["message"]
    return render_template("answer.html", message=message)


@bp.route("/about", methods=["GET"])
def about():
    return render_template("about.html")

binge/templates/about.html
{% extends 'base.html' %}

{% block content%}

This is about page.

{% endblock %}

binge/templates/answer.html
{% extends 'base.html' %}

{% block content%}
    {{ session.message }}
{% endblock %}

binge/templates/base.html
<!doctype html>
<html lang="en" class="h-100">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">
    <title>Cover Template · Bootstrap v5.0</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/cover/">

    

    <!-- Bootstrap core CSS -->
<link href="{{ url_for('static', filename='/assets/dist/css/bootstrap.min.css')}}" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    
    <!-- Custom styles for this template -->
    <link href="{{ url_for('static', filename='cover.css')}}" rel="stylesheet">
  </head>
  <body class="d-flex h-100 text-center text-white bg-dark">
    
<div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
  <header class="mb-auto">
    <div>
      <nav class="nav nav-masthead justify-content-center float-md-start">
        <a class="nav-link active" aria-current="page" href="{{ url_for('routes.main_page') }}">Home</a>
        <a class="nav-link" href="{{ url_for('routes.about') }}">About</a>
      </nav>
    </div>
  </header>

  <main class="px-3">
    {% block content %}{% endblock content %}
    
  </main>

  <footer class="mt-auto text-white-50">
    <p>Cover template for <a href="https://getbootstrap.com/" class="text-white">Bootstrap</a>, by <a href="https://twitter.com/mdo" class="text-white">@mdo</a>.</p>
  </footer>
</div>


    
  </body>
</html>

binge/templates/home.html
{% extends 'base.html' %}

{% block content%}

<p class="h2">What series do you want to binge?</p>

    <form method="POST">
        <div class="input-group">
            {{ form.csrf_token }}
            {{ form.title(size=20, class="form-control") }}
            {{ form.find_it(class="btn btn-secondary") }}
        </div>
    </form>

{% endblock %}

binge/templates/title.html
{% extends 'base.html' %}

{% block content%}

<div class="col">
    <div class="card">
      <div class="row g-0">
        <div class="col-md-4">
            <img src="{{ title_data.image }}" alt="{{ url_for('static', filename='placeholder.jpg') }}" width="200" height="300">
        </div>
        <div class="col-md-8">
          <div class="card-body">
            <h5 class="float-md-start mb-0 text-muted">{{ title_data.title }}</h5>
            <p class="card-text text-muted">{{ title_data.description }}</p>
            <p class="card-text"><small class="text-muted">Sesons: {{ title_data.seasons }}</small></p>
          </div>
        </div>
      </div>
    </div>
  </div>
<div>
  <p class="h2">I want to binge it in</p>

    <form method="POST">
        <div class="input-group">
            {{ form.csrf_token }}
            {{ form.duration }} 
            {{ form.peroid }}
            {{ form.go }}
        </div>
    </form>

</div>
{% endblock %}